# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  [context.production.environment]
    API_URL = "https://koeching-backend.herokuapp.com"
    BACKEND_URL = "https://koeching-backend.herokuapp.com/graphql"